version: "3.2"

networks:
  my_network:
    driver: bridge

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_DB=DB_food_order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - my_network

  app:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - POSTGRES_DB=DB_food_order
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    networks:
      - my_network
